# Generated by Django 5.2.4 on 2025-09-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
