# Generated by Django 5.2.4 on 2025-09-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('lecturer', models.CharField(blank=True, max_length=200, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
