# Generated by Django 5.2.4 on 2025-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
