# Generated by Django 5.2.4 on 2025-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_counselingsession_ecounselingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('marks_obtained', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
