# Generated by Django 5.2.4 on 2025-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
